version: '3.8'
services:
  db: 
    image: postgres:14.1-alpine
    restart: always
    environment:       
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  web:
   build: .
   command:
    bundle exec rails db:prepare 
    bundle exec rails s -p 3000 -b '0.0.0.0'
   volumes: 
      - ".:/app"
   ports:
     - "3001:3000"
   depends_on:
     - db
   links:
     - db
   environment:
    DB_USER: postgres
    DB_NAME: resultporcessing-docker-dev
    DB_PASSWORD: postgres
    DB_HOST: db
  worker:
   build: .
   command: rake jobs:work
   volumes: 
      - ".:/app" 
   depends_on:
     - db
   links:
     - db
   environment:
    DB_USER: postgres
    DB_NAME: resultporcessing-docker-dev
    DB_PASSWORD: postgres
    DB_HOST: db

volumes:
    db:
      driver: local

